// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVSEQ7cwjW1dfhMrwA6ZrWWI3YRtPT8AM',
    appId: '1:770260295458:web:a8368b62ddf86927618f7b',
    messagingSenderId: '770260295458',
    projectId: 'twitterclient-8edef',
    authDomain: 'twitterclient-8edef.firebaseapp.com',
    storageBucket: 'twitterclient-8edef.appspot.com',
    measurementId: 'G-HZDRB451TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxLy74Dyhg-dtzW4smM62ZfbgnElK2thE',
    appId: '1:770260295458:android:a9fd15694961619d618f7b',
    messagingSenderId: '770260295458',
    projectId: 'twitterclient-8edef',
    storageBucket: 'twitterclient-8edef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIKq_ksVhJ2JBfuPOyURjZDXLKlSMLu44',
    appId: '1:770260295458:ios:9412b0ce0cbd6856618f7b',
    messagingSenderId: '770260295458',
    projectId: 'twitterclient-8edef',
    storageBucket: 'twitterclient-8edef.appspot.com',
    iosClientId: '770260295458-busu7f37qkecjf09d409b7g2j42tk68v.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClient',
  );
}
